#!/usr/bin/env python3
import re
import json
import subprocess
import hashlib
import concurrent.futures

EPG_ID_MAP = {
    # Globos/AFILIADAS GLOBO
    "Globo Mogi das Cruzes": "tv-globo-sp",
    "Globo Nordeste FHD": "globo.nordeste.br",
    "Globo TV Verdes Mares Fortaleza FHD": "a.e.br",
    "Globo TV Verdes Mares Fortaleza HD": "a.e.br",
    "Globo TV Bahia FHD": "tvsbahia.ba.gov.br",
    "Globo TV Bahia HD": "tvsbahia.ba.gov.br",
    "Globo TV Bahia": "tvsbahia.ba.gov.br",
    "Globo TV Anhanguera FHD": "tv.anhanguera.br",
    "Globo TV Anhanguera HD": "tv.anhanguera.br",
    "Globo TV Anhanguera": "tv.anhanguera.br",
    "Globo Brasília FHD": "tvglobo.bsb.br",
    "Globo Brasília HD": "tvglobo.bsb.br",
    "Globo Brasília": "tvglobo.bsb.br",
    "Globo RBS Porto Alegre HD": "rbs.rio.grande.br",
    "Globo RPC Curitiba FHD": "rpc.curitiba.br",
    "Globo RPC Curitiba HD": "rpc.curitiba.br",
    "Globo RPC Curitiba HD²": "rpc.curitiba.br",
    "Globo RPC Curitiba Alternativo HD": "rpc.curitiba.br",
    "Globo RPC Curitiba Alternativo": "rpc.curitiba.br",
    "Globo RPC Londrina FHD": "rpc.curitiba.br",
    "Globo RPC Londrina HD": "rpc.curitiba.br",
    "Globo RPC Londrina": "rpc.curitiba.br",
    "Globo RPC Foz do Iguaçu FHD": "rpc.curitiba.br",
    "Globo RPC Foz do Iguaçu HD": "rpc.curitiba.br",
    "Globo RPC Foz do Iguaçu": "rpc.curitiba.br",
    "Globo RPC Maringa FHD": "rpc.curitiba.br",
    "Globo RPC Maringa HD": "rpc.curitiba.br",
    "Globo RPC Maringa": "rpc.curitiba.br",
    "Globo RPC Cascavel FHD": "rpc.curitiba.br",
    "Globo RPC Cascavel HD": "rpc.curitiba.br",
    "Globo RPC Cascavel": "rpc.curitiba.br",
    "Globo RPC TV Paranavai FHD": "rpc.curitiba.br",
    "Globo RPC TV Paranavai HD": "rpc.curitiba.br",
    "Globo RPC TV Paranavai": "rpc.curitiba.br",
    "Globo RPC TV Ponta Grossa FHD": "rpc.curitiba.br",
    "Globo RPC TV Ponta Grossa HD": "rpc.curitiba.br",
    "Globo RPC TV Ponta Grossa": "rpc.curitiba.br",
    "Globo RBS TV Pelotas HD": "globo.br",
    "Globo RBS TV Caxias do Sul": "globo.br",
    "Globo RBS TV Passo Fundo FHD": "globo.br",
    "Globo RBS TV Passo Fundo HD": "globo.br",
    "Globo RBS TV Passo Fundo": "globo.br",
    "Globo RBS TV Santa Maria FHD": "rbs.santa.maria.br",
    "Globo RBS TV Santa Maria HD": "rbs.santa.maria.br",
    "Globo EPTV Sul de Minas HD": "br#eptv-sul-de-minas-hd",
    "Globo TV Vanguarda Taubate FHD": "br#globo-sp",
    "Globo NSC TV Florianopolis FHD": "nsc.florianopolis.br",
    "Globo NSC TV Florianopolis HD": "nsc.florianopolis.br",
    "Globo NSC TV Joinville FHD": "nsc.joinville.br",
    "Globo NSC TV Joinville HD": "nsc.joinville.br",
    "Globo NSC TV Chapecó FHD": "nsc.chapeco.br",
    "Globo NSC TV Criciuma FHD": "globo.br",
    "Globo NSC TV Criciuma HD": "globo.br",
    "Globo NSC TV Criciuma": "globo.br",
    "Globo NSC TV Centro Oeste FHD": "globo.br",
    "Globo NSC TV Centro Oeste HD": "globo.br",
    "Globo NSC TV Centro Oeste": "globo.br",
    "Globo NSC TV Blumenau FHD": "nsc.blumenau.br",
    "Globo NSC TV Blumenau HD": "nsc.blumenau.br",
    "Globo TV Sergipe FHD": "TVSergipe.br",
    "Globo TV Sergipe HD": "TVSergipe.br",
    "Globo TV Sergipe": "TVSergipe.br",
    "Globo TV Santa Cruz FHD": "tv.santa.cruz.br",
    "Globo TV Santa Cruz HD": "tv.santa.cruz.br",
    "Globo TV Santa Cruz": "tv.santa.cruz.br",
    "Globo TV Rio Sul FHD": "TVRioSul.br",
    "Globo TV Rio Sul HD": "TVRioSul.br",
    "Globo TV Rio Sul": "TVRioSul.br",
    "Globo TV Liberal Belem FHD": "tv.liberal.br",
    "Globo TV Liberal Belem HD": "tv.liberal.br",
    "Globo TV Liberal Belem": "tv.liberal.br",
    "Globo TV Rede Amazonica Manaus FHD": "globo.amazonas.br",
    "Globo TV Rede Amazonica Manaus HD": "globo.amazonas.br",
    "Globo TV Rede Amazonica Manaus": "globo.amazonas.br",
    "Globo TV Rede Amazonica Boa Vista FHD": "globo.amazonas.br",
    "Globo TV Rede Amazonica Boa Vista HD": "globo.amazonas.br",
    "Globo TV Rede Amazonica Boa Vista": "globo.amazonas.br",
    "Globo TV Rede Amazonica Porto Velho FHD": "globo.amazonas.br",
    "Globo TV Rede Amazonica Porto Velho HD": "globo.amazonas.br",
    "Globo TV Rede Amazonica Porto Velho": "globo.amazonas.br",
    "Globo TV Asa Branca FHD": "tv.morena.br",
    "Globo TV Asa Branca HD": "tv.morena.br",
    "Globo TV Asa Branca": "tv.morena.br",
    "Globo TV Morena Campo Grande FHD": "tv.morena.br",
    "Globo TV Morena Campo Grande HD": "tv.morena.br",
    "Globo TV Morena Campo Grande": "tv.morena.br",
    "Globo TV Morena FHD": "tv.morena.br",
    "Globo TV Morena HD": "tv.morena.br",
    "Globo TV Morena": "tv.morena.br",
    "Globo TV Mirante São Luis FHD": "tv.mirante.sao.luis.br",
    "Globo TV Mirante São Luis HD": "tv.mirante.sao.luis.br",
    "Globo TV Mirante São Luis": "tv.mirante.sao.luis.br",
    "Globo TV Mirante Cocais FHD": "tv.mirante.sao.luis.br",
    "Globo TV Mirante Cocais HD": "tv.mirante.sao.luis.br",
    "Globo TV Mirante Cocais": "tv.mirante.sao.luis.br",
    "Globo TV Gazeta Vitoria FHD": "TVGazeta.br",
    "Globo TV Gazeta Vitoria HD": "TVGazeta.br",
    "Globo TV Gazeta Vitoria": "TVGazeta.br",
    "Globo TV Gazeta Sul ES FHD": "tv.gazeta.sul.br",
    "Globo TV Gazeta Sul ES HD": "tv.gazeta.sul.br",
    "Globo TV Gazeta Alagoas FHD": "globo.br",
    "Globo TV Gazeta Alagoas HD": "globo.br",
    "Globo TV Gazeta Alagoas": "globo.br",
    "Globo TV Verdes Mares Cariri FHD": "a.e.br",
    "Globo TV Verdes Mares Cariri HD": "a.e.br",
    "Globo TV Verde Mares Cariri": "a.e.br",
    "Globo Inter TV Alto Litoral FHD": "InterTVAltoLitoral.br",
    "Globo Inter TV Alto Litoral HD": "InterTVAltoLitoral.br",
    "Globo Inter TV Alto Litoral": "InterTVAltoLitoral.br",
    "Globo Inter TV Cabugi FHD": "globo.sp.br",
    "Globo Inter TV Cabugi HD": "globo.sp.br",
    "Globo Inter TV Cabugi": "globo.sp.br",
    "Globo RBS TV POA FHD": "rbs.rio.grande.br",
    "Globo RBS TV POA HD": "rbs.rio.grande.br",
    "Globo Inter TV Serra Mar FHD": "InterTVSerraPlusMar.br",
    "Globo Inter TV Serra Mar HD": "InterTVSerraPlusMar.br",
    "Globo Inter TV Serra Mar": "InterTVSerraPlusMar.br",
    "Globo TV Clube Teresina FHD": "tv.clube.br",
    "Globo TV Clube Teresina HD": "tv.clube.br",
    "Globo TV Clube Teresina": "tv.clube.br",
    "Globo TV Cabo Branco FHD": "tv.cabo.branco.br",
    "Globo TV Cabo Branco HD": "tv.cabo.branco.br",
    "Globo TV Cabo Branco": "tv.cabo.branco.br",
    "Globo TV C. America Cuiaba FHD": "tv.centro.america.cuiaba.br",
    "Globo TV C. America Cuiaba HD": "tv.centro.america.cuiaba.br",
    "Globo TV C. America Cuiaba": "tv.centro.america.cuiaba.br",
    "Globo TV Subae FHD": "globo.br",
    "Globo TV Subae HD": "globo.br",
    "Globo TV Subae": "globo.br",
    "Globo TV Sudoeste FHD": "globo.br",
    "Globo TV Sudoeste HD": "globo.br",
    "Globo TV Sudoeste": "globo.br",
    "Globo Inter TV dos Vales FHD": "InterTVGrandeMinas.br",
    "Globo Inter TV dos Vales HD": "InterTVGrandeMinas.br",
    "Globo Inter TV dos Vales": "InterTVGrandeMinas.br",
    "Globo TV Anhanguera Rio Verde HD": "tv.anhanguera.br",
    "Globo TV Anhanguera Rio Verde": "tv.anhanguera.br",
    "Globo TV Anhanguera Jatai HD": "tv.anhanguera.br",
    "Globo TV Anhanguera Jatai": "tv.anhanguera.br",
    "Globo TV Anhanguera Itumbiara HD": "tv.anhanguera.br",
    "Globo TV Anhanguera Itumbiara": "tv.anhanguera.br",
    "Globo TV Anhanguera Luziania HD": "tv.anhanguera.br",
    "Globo TV Anhanguera Luziania": "tv.anhanguera.br",
    "Globo TV Anhanguera Catalão": "tv.anhanguera.br",
    "Globo TV Morena Corumba": "tv.morena.br",
    "Globo TV Liberal Castanhal": "tv.liberal.br",
    "Globo Inter TV Grande Minas FHD": "InterTVGrandeMinas.br",
    "Globo Inter TV Grande Minas HD": "InterTVGrandeMinas.br",
    "Globo Inter TV Grande Minas": "InterTVGrandeMinas.br",
    "Globo TV Integração Araxa HD": "br#globo-belo-horizonte-hd",
    "Globo TV Integração Araxa": "br#globo-belo-horizonte-hd",
    "Globo TV Integração Uberaba HD": "br#globo-belo-horizonte-hd",
    "Globo TV Integração Uberaba": "br#globo-belo-horizonte-hd",
    "Globo TV Integração Juiz de Fora HD": "br#globo-belo-horizonte-hd",
    "Globo TV Integração Juiz de Fora": "br#globo-belo-horizonte-hd",
    "Globo TV Mirante Balsas": "globo.br",
    "Globo TV Mirante Imperatriz": "globo.br",
    "Globo TV Morena Ponta Pora": "tv.morena.br",
    "Globo RBS Santa Maria": "rbs.santa.maria.br",
    "Globo RBS TV Uruguaiana": "globo.br",
    "Globo RBS Erechim": "globo.br",
    "Globo RBS dos Vales": "globo.br",
    "Globo RBS Santa Rosa": "globo.br",
    "Globo RBS Rio Grande": "globo.br",
    "Globo RBS Cruz Alta": "globo.br",
    "Globo RBS Bage HD": "globo.br",
    "Globo Rede Amazonica Cruzeiro do Sul": "rede.amazonica.manaus.br",
    "Globo Rede Amazonica Guajara Mirim": "globo.br",
    "Globo Rede Amazonica Itacoatiara": "rede.amazonica.manaus.br",
    "Globo Rede Amazonica Ji-Parana": "rede.amazonica.rio.branco.br",
    "Globo Rede Amazonica Macapa": "globo.br",
    "Globo Rede Amazonica Parinstins": "globo.br",
    "Globo Rede Amazonica Vilhena": "globo.br",
    "Globo Palmas TO": "tv.anhanguera.br",
    "Globo RPC Guarapuava": "rpc.curitiba.br",
    "Globo TV Liberal Redencao": "tv.liberal.br",
    
    # RECORD
    "Record Belem": "br#recordtv-belem-hd",
    "Record Campinas HD": "record.br",
    "Record Campinas": "record.br",
    "Record Santa Catarina": "record.br",
    "Record Parana": "record.br",
    "Record TV Cabralia": "record.br",
    "Record Portugal": "record.br",
    
    # SBT
    "SBT TV Aratu BA": "SBTNacional.br",
    "SBT TV Alterosa": "SBTNacional.br",
    
    # ABERTOS
    "TV Gazeta SP FHD": "TVGazeta.br",
    "TV Gazeta SP  HD": "TVGazeta.br",
    "TV Gazeta SP": "TVGazeta.br",
    "TV Câmara HD": "tv.camara.leg.br",
    "TV Justiça HD": "tv.justica.leg.br",
    "TV Justica": "tv.justica.leg.br",
    "TV Senado": "tv.senado.leg.br",
    "TV Cultura PA": "TVCulturaNacional.br",
    "Futura FHD": "futura.br",
    "Futura": "futura.br",
    "Canal do Boi HD": "canal-do-boi",
    "Canal do Boi": "canal-do-boi",
    "Canal Rural": "canal-rural",
    
    # VARIEDADES
    "Multishow": "multishow",
    "GNT FHD": "gnt",
    "GNT": "gnt",
    "OFF FHD": "off",
    "Lifetime HD": "lifetime",
    "Lifetime FHD": "lifetime",
    "Lifetime": "lifetime",
    "TLC HD": "tlc",
    "TLC FHD": "tlc",
    "TLC": "tlc",
    "A&E FHD": "a-e",
    "A&E": "a-e",
    "Food Network FHD": "food-network",
    "Food Network": "food-network",
    "Curta!": "curta-menos",
    "Arte 1 FHD": "arte-1",
    "Arte 1": "arte-1",
    "Fish TV HD": "fish-tv",
    "Fish TV FHD": "fish-tv",
    "Fish TV": "fish-tv",
    "E!": "e",
    "Woohoo HD": "woohoo",
    "Urban TV": "urban-tv",
    "Sabor & Arte": "sabor-arte",
    "Prime Box Brasil": "prime-box-brasil",
    "Polishop TV": "polishop",
    "Music Box Brasil HD": "music-box-brasil",
    
    # FILMES & SERIES
    "TNT HD": "tnt",
    "TNT FHD": "tnt",
    "TNT Alternativo HD": "tnt",
    "TNT Series": "tnt-series",
    "TNT Series HD": "tnt-series",
    "TNT Series FHD": "tnt-series",
    "TNT Novelas HD": "tnt-novelas",
    "TNT Novelas FHD": "tnt-novelas",
    "TNT Novelas": "tnt-novelas",
    "Warner Channel HD": "warner-channel",
    "TCM": "tcm",
    "TCM FHD": "tcm",
    "Studio Universal": "studio-universal",
    "Studio Universal HD": "studio-universal",
    "Universal Premiere FHD": "universal-premiere",
    
    # ESPORTES
    "SporTV FHD": "br#sportv-hd",
    "SporTV HD": "br#sportv-hd",
    "SporTV": "br#sportv-hd",
    "SporTV 4k": "br#sportv-hd",
    "SporTV Alternativo HD": "br#sportv-hd",
    "SporTV 2 FHD": "br#sportv2-hd",
    "SporTV 2 HD": "br#sportv2-hd",
    "SporTV 2": "br#sportv2-hd",
    "SporTV 3 FHD": "br#sportv3-hd",
    "SporTV 3 HD": "br#sportv3-hd",
    "SporTV 3": "br#sportv3-hd",
    "Xsports HD": "xsports",
    "Xsports FHD": "xsports",
    "GE TV HD": "ge-tv",
    "GE TV FHD": "ge-tv",
    "Redbull TV": "red-bull-tv",
    
    # ESPN
    "ESPN": "espn-brasil",
    "ESPN 4k": "espn-brasil",
    "ESPN Alternativo HD": "espn-brasil",
    "ESPN 4 HD": "espn-4",
    "ESPN 4 Alternativo HD": "espn-4",
    "ESPN 2 FHD": "espn-2",
    "Espn 2": "espn-2",
    "ESPN 2 FHD²": "espn-2",
    "ESPN 3 HD": "espn-3",
    "ESPN 3": "espn-3",
    "ESPN 3 FHD²": "espn-3",
    "ESPN 3 Alternativo HD": "espn-3",
    "ESPN 5 HD": "espn-5",
    "ESPN 5 Alternativo HD": "espn-5",
    
    # INFANTIS
    "Tooncast": "tooncast",
    "TV Ra Tim Bum": "tv-ra-tim-bum",
    "TV Ra Tim Bum HD": "tv-ra-tim-bum",
    "TV Ra Tim Bum FHD": "tv-ra-tim-bum",
    
    # NOTICIAS
    "BBC World News": "bbc-world-news",
    "SBT News FHD": "sbt-news",
    "SBT News HD": "sbt-news",
    "SBT News": "sbt-news",
    "FOX News": "fox-news",
    "RAI News 24hs": "rai-news",
    
    # PREMIERE
    "Premiere 2 FHD": "premiere-2",
    "Premiere 2 HD": "premiere-2",
    "Premiere 2": "premiere-2",
    "Premiere 3 FHD": "premiere-3",
    "Premiere 3 HD": "premiere-3",
    "Premiere 3": "premiere-3",
    "Premiere 4 FHD": "premiere-4",
    "Premiere 4 HD": "premiere-4",
    "Premiere 4": "premiere-4",
    "Premiere 5 FHD": "premiere-5",
    "Premiere 5 HD": "premiere-5",
    "Premiere 5": "premiere-5",
    "Premiere 6 FHD": "premiere-6",
    "Premiere 6 HD": "premiere-6",
    "Premiere 6": "premiere-6",
    "Premiere 7 FHD": "premiere-7",
    "Premiere 7 HD": "premiere-7",
    "Premiere 7": "premiere-7",
    "Premiere 8 FHD": "premiere-8",
    "Premiere 8 HD": "premiere-8",
    "Premiere 8": "premiere-8",
    "Premiere 9 FHD": "premiere-9",
    "Premiere 9 HD": "premiere-9",
    "Premiere 9": "premiere-9",
    
    # PARAMOUNT+
    "Paramount+ 1 FHD": "paramount-plus",
    "Paramount+ 1 HD": "paramount-plus",
    "Paramount+ 1": "paramount-plus",
    "Paramount+ 2 FHD": "paramount-plus",
    "Paramount+ 2 HD": "paramount-plus",
    "Paramount+ 2": "paramount-plus",
    
    # GLOBOS | NORTE (TV Anhanguera, TV Liberal, TV Tapajos)
    "TV ANHANGUERA": "tv-globo-goias",
    "TV ANHANGUERA HD": "tv-globo-goias",
    "TV ANHANGUERA ANAPOLIS": "tv-globo-goias",
    "TV ANHANGUERA ANAPOLIS HD": "tv-globo-goias",
    "TV ANHANGUERA CATALAO": "tv-globo-goias",
    "TV ANHANGUERA CATALAO HD": "tv-globo-goias",
    "TV ANHANGUERA GURUPI": "tv-globo-goias",
    "TV ANHANGUERA GURUPI HD": "tv-globo-goias",
    "TV ANHANGUERA ITUMBIARA": "tv-globo-goias",
    "TV ANHANGUERA ITUMBIARA HD": "tv-globo-goias",
    "TV ANHANGUERA JATAI": "tv-globo-goias",
    "TV ANHANGUERA JATAI HD": "tv-globo-goias",
    "TV ANHANGUERA LUZIANIA": "tv-globo-goias",
    "TV ANHANGUERA LUZIANIA HD": "tv-globo-goias",
    "TV ANHANGUERA PORANGATU": "tv-globo-goias",
    "TV ANHANGUERA PORANGATU HD": "tv-globo-goias",
    "TV ANHANGUERA RIO VERDE": "tv-globo-goias",
    "TV ANHANGUERA RIO VERDE HD": "tv-globo-goias",
    "TV LIBERAL": "tv-globo-pa",
    "TV LIBERAL ALTAMIRA HD": "tv-globo-pa",
    "TV LIBERAL ALTAMRIA": "tv-globo-pa",
    "TV LIBERAL CASTANHAL": "tv-globo-pa",
    "TV LIBERAL MARABA": "tv-globo-pa",
    "TV LIBERAL MARABA HD": "tv-globo-pa",
    "TV LIBERAL PARAGOMINAS": "tv-globo-pa",
    "TV LIBERAL PARAGOMINAS HD": "tv-globo-pa",
    "TV LIBERAL PARAUAPEBAS": "tv-globo-pa",
    "TV LIBERAL PARAUAPEBAS HD": "tv-globo-pa",
    "TV LIBERAL REDENCAO": "tv-globo-pa",
    "TV LIBERAL RENDENCAO": "tv-globo-pa",
    "TV TAPAJOS": "tv-globo-pa",
    "TV TAPAJOS HD": "tv-globo-pa",
    
    # GLOBOS | CENTRO-OESTE
    "TV CENTRO AMERICA": "tv-globo-mt",
    "TV CENTRO AMERICA NORTE": "tv-globo-mt",
    "TV CENTRO AMERICA NORTE HD": "tv-globo-mt",
    "TV CENTRO AMERICA SUL": "tv-globo-mt",
    "TV CENTRO AMERICA SUL HD": "tv-globo-mt",
    "TV CENTRO AMERICA TANGARA DA SERRA": "tv-globo-mt",
    "TV CENTRO AMERICA TANGARA DA SERRA HD": "tv-globo-mt",
    "TV MORENA CORUMBA": "tv-globo-ms",
    "TV MORENA CORUMBA HD": "tv-globo-ms",
    "TV MORENA PONTA PORA": "tv-globo-ms",
    "TV MORENA PONTA PORA HD": "tv-globo-ms",
    
    # GLOBOS | NORDESTE
    "TV ALVORADA": "tv.globo.ba",
    "TV ALVORADA HD": "tv.globo.ba",
    "TV GRANDE RIO": "tv.globo.pi",
    "TV GRANDE RIO HD": "tv.globo.pi",
    "TV MIRANTE BALSAS": "tv.globo.ma",
    "TV MIRANTE BALSAS HD": "tv.globo.ma",
    "TV MIRANTE IMPERATRIZ": "tv.globo.ma",
    "TV MIRANTE IMPERATRIZ HD": "tv.globo.ma",
    "TV OESTE": "tv.globo.ba",
    "TV OESTE HD": "tv.globo.ba",
    "TV PARAIBA": "tv.globo.pb",
    "TV PARAIBA HD": "tv.globo.pb",
    "TV SAO FRANCISCO": "tv.globo.se",
    "TV SAO FRANCISCO HD": "tv.globo.se",
}

def extract_channel_name(line):
    match = re.search(r'tvg-name="([^"]+)"', line)
    if match:
        return match.group(1).strip()
    return None

def find_epg_id(channel_name):
    for name, epg_id in EPG_ID_MAP.items():
        if name.lower() in channel_name.lower():
            return epg_id
    return None

def process_m3u(input_file, output_file):
    with open(input_file, 'r', encoding='utf-8') as f:
        lines = f.readlines()
    
    updated_lines = []
    stats = {"total": 0, "updated": 0, "already_has": 0, "not_found": 0}
    
    for line in lines:
        if line.startswith('#EXTINF:'):
            stats["total"] += 1
            if 'tvg-id=""' in line or 'tvg-id=" "' in line or 'tvg-id="' not in line:
                channel_name = extract_channel_name(line)
                epg_id = find_epg_id(channel_name) if channel_name else None
                
                if epg_id:
                    line = re.sub(r'tvg-id="[^"]*"', f'tvg-id="{epg_id}"', line)
                    stats["updated"] += 1
                else:
                    stats["not_found"] += 1
            else:
                stats["already_has"] += 1
        updated_lines.append(line)
    
    with open(output_file, 'w', encoding='utf-8') as f:
        f.writelines(updated_lines)
    
    print(f"Total channels: {stats['total']}")
    print(f"Updated with EPG: {stats['updated']}")
    print(f"Already had EPG: {stats['already_has']}")
    print(f"Not found EPG: {stats['not_found']}")
    
    return stats

if __name__ == "__main__":
    stats = process_m3u('lista5.m3u', 'lista5_updated.m3u')
