name: ya

on:
  workflow_dispatch:

jobs:
  opencode:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install OpenCode
        run: |
          curl -fsSL https://opencode.ai/install | bash
          echo "$HOME/.opencode/bin" >> $GITHUB_PATH

      - name: Create prompt
        run: |
          cat << 'EOF' > prompt.txt
          LEIA https://timesbrasil.com.br/%20https://www.cnnbrasil.com.br/money/%20https://valor.globo.com/%20https://investnews.com.br/%20https://www.bloomberglinea.com.br/
          E ME DIGA O QUE COMPRAR OU VENDER HOJE, NA B3 PARA DIVIDENDOS

          EOF

      - name: Run OpenCode
        run: |
          opencode run "$(cat prompt.txt)"

      - name: Commit corrected file
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add GLOBO.py

          git commit -m "Correção automática de GLOBO.py" || echo "Nada para commit"

          git push
