name: Remove XML Files

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */8 * * *"

jobs:
  clean-xml:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Remover arquivos XML
        run: |
          echo "Removendo todos os arquivos .xml..."
          find . -type f -name "*.xml" -delete

      - name: Commit alterações
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add . || true
          git commit -m "Remoção automática de arquivos XML" || echo "Nada para commit"
          git push origin HEAD || echo "Falha ao dar push"
          
